#!/bin/bash

rm nvc_main.x

CXX="/opt/nvidia/hpc_sdk/Linux_x86_64/25.11/compilers/bin/nvc++"

LINKFLAG="-L/opt/nvidia/hpc_sdk/Linux_x86_64/25.11/cuda/lib64 -L/usr/lib64/ -L/opt/local/lib/gcc11/ -L/home/ubuntu/mofsim/.pixi/envs/default/lib/python3.12/site-packages/torch/lib -ltorch -ltorch_cpu -lc10 -Wl,-rpath,/home/ubuntu/mofsim/.pixi/envs/default/lib/python3.12/site-packages/torch/lib"

NVCFLAG="-O3 -std=c++20 -target=gpu -Minline -fopenmp -cuda -stdpar=multicore -I/home/ubuntu/mofsim/.pixi/envs/default/lib/python3.12/site-packages/torch/include -I/home/ubuntu/mofsim/.pixi/envs/default/lib/python3.12/site-packages/torch/include/torch/csrc/api/include"

$CXX $NVCFLAG $LINKFLAG -c axpy.cu && echo "Finished axpy.cu" &

$CXX $NVCFLAG $LINKFLAG -c main.cpp && echo "Finished main.cpp" &

$CXX $NVCFLAG $LINKFLAG -c read_data.cpp && echo "Finished read_data.cpp" &

$CXX $NVCFLAG $LINKFLAG -c data_struct.cpp && echo "Finished data_struct.cpp" &

$CXX $NVCFLAG $LINKFLAG -c VDW_Coulomb.cu && echo "Finished VDW_Coulomb.cu" &

wait

$CXX $NVCFLAG $LINKFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x ; echo "Finished Linking"

rm *.o
